GET http://localhost:4011/api/details


###
post http://localhost:4011/api/details/create
content-type: application/json

{
    "email": "youadcxas@me.com",
    "first_name": "Neddvsa",
    "last_name": "sufgdK",
    "occupation": "Soujtadsware Engineer",
    "numbers": 454,
    "addresss":"Westdene johannesburg Gauteng",
    "password_hash" : "d1h2hg3"
}

###
post http://localhost:4011/api/details/deleteUser
content-type: application/json

{

    "email": "youadcxas@me.com"
}

###
POST http://localhost:4011/api/details/updateUser
content-type: application/json

{
    "email": "youaxas@me.com",
    "first_name": "Nevaasfha",
    "last_name": "sfadahfK",
    "occupation": "Softsfhfware Engineer",
    "password_hash": "12fhf3"
   
}

###
POST http://localhost:4011/api/details/login
content-type: application/json

{
                                                         
    "email": "user@example.com",
    "password_hash": "123"

}

###
POST http://localhost:4011/api/details/aim
content-type: application/json

{
                                                         
    "brief": "I want to do a shallow foundation slope analysis ",
    "first_name": "Johny"

}


###

POST http://localhost:4011/api/details/UserComments 
content-type: application/json

{
                                                         
    "comment": "I want to do a shallow foundation slope analysis analysis ",
    "first_name": "Johnny"

}





